config/routes.rb
Rails.application.routes.draw do

  
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resource :showcase do 
		collection do 
			get :school_showcase
		end
	end

	resources :students do 
		get :pay_fees_school
		post :pay_fees_school
		get :fee_details
		get :pay_fees_tutor
		post :pay_fees_tutor
		get :sale_book
		post :sale_book 
		get :schools
		get :apply_school
		post :apply_school
		get :teachers
		get :apply_teacher
		post :apply_teacher
		get :slots
	end

	resources :teachers do
		get :schools
		get :students
		get :apply_school
		post :apply_school
		get :find_student
		get :sale_notes
		get :create_sale_notes
		post :create_sale_notes
		get :update_sale_notes
		patch :update_sale_notes
		get :sale
		get :destroy_sale_notes
		get :slots
		get :create_slots
		post :create_slots
		get :update_slots
		patch :update_slots
		get :destroy_slot
		get :demo_videos
		get :create_demo_videos
		post :create_demo_videos
		get :update_demo_videos
		patch :update_demo_videos
		get :destroy_demo_video
		get :teacher_openings
	end

	resources :schools do
		get :teachers
		get :vendors
		get :students
		get :overview
		post :overview
		get :update_overview
		patch :update_overview
		get :courses
		get :course
		post :course
		get :update_course
		patch :update_course
		get :destroy_course
		get :scholarships
		get :scholarship
		post :scholarship
		get :update_scholarship
		patch :update_scholarship
		get :destroy_scholarship
		get :placements
		get :placement
		post :placement
		get :update_placement
		patch :update_placement
		get :destroy_placement
		get :cutoffs
		get :cutoff
		post :cutoff
		get :update_cutoff
		patch :update_cutoff
		get :destroy_cutoff
		get :campus
		get :campu
		post :campu
		get :update_campu
		patch :update_campu
		get :destroy_campu
		get	:schoolinformations
		get  :schoolinformation
		post :schoolinformation
		get :update_schoolinformation
		patch :update_schoolinformation
		get :destroy_schoolinformation
		get :schoolpictures
		get  :schoolpicture
		post :schoolpicture
		get :update_schoolpicture
		patch :update_schoolpicture
		get :destroy_schoolpicture
		get :schoolvideos
		get  :schoolvideo
		post :schoolvideo
		get :update_schoolvideo
		patch :update_schoolvideo
		get :destroy_schoolvideo
		get :post_requirements
		post :teacher_requirement
		post :vendor_requirement
	end

	resources :vendors do
		get :schools
		get :vendor_openings
		get :apply_school
		post :apply_school
	end

	root to: "users#index"
	devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks",
	 sessions: 'users/sessions' ,registrations: 'users/registrations',passwords: 'users/passwords'}
		devise_scope :user do 
			get '/users/login' => 'devise/sessions#new'
		    get '/users/register' => 'devise/registrations#new'
		    get '/users/sign_out' => 'devise/sessions#destroy'
		    #get '/users/:id/showcase' => 'users#showcase'
		end
	devise_for :admins, controllers: { sessions: 'admins/sessions'}
	devise_scope :admin do 
			get '/admins/login' => 'devise/sessions#new'
		    get '/admins/sign_out' => 'devise/sessions#destroy'
		    #get '/users/:id/showcase' => 'users#showcase'
		end
	resources :admins do 
		get :schools
		get :school_update
		patch :school_update
		get :teachers
		get :students
		get :vendors
		post :activate
		get :video_upload
		post :video_upload
	end
	  get 'users/search' 
	  post 'users/search'
	  get 'users/student_show'
	  get 'users/show'
	  get 'users/all_view'
	  post 'users/find_all_course_name'
	  get 'users/current_requirements'
	  get 'users/apply_to_post'
end

app/views/admins/_top.html.erb
<div id="top">
        <!-- .navbar -->
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <header class="navbar-header">
                    <%= link_to image_tag('logoedu.png',class: "img-responsive DashLogo"),admins_path, class: "navbar-brand" %>
                </header>
        		<div class="topnav">
                    <div class="btn-group">
                        <a data-toggle="modal" data-original-title="Help" data-placement="bottom"
                           class="btn btn-default btn-sm"
                           href="#helpModal">
                            <i class="fa fa-question"></i>
                        </a>
                    </div>
                    <div class="btn-group">
                        <%= link_to "",destroy_admin_session_path,class: "btn btn-metis-1 btn-sm fa fa-power-off" %>
                    </div>
                    <div class="btn-group">
                        <a data-placement="bottom" data-original-title="Show / Hide Left" data-toggle="tooltip"
                           class="btn btn-primary btn-sm toggle-left" id="menu-toggle">
                            <i class="fa fa-bars"></i>
                        </a>
                    </div>
                </div>
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                </div>
            </div>
            <!-- /.container-fluid -->
        </nav>
        <!-- /.navbar -->
    </div>
    <!-- /#top -->

app/views/admins/schools.html.erb
<title>Admin Dashboard</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= render "layouts/stylesheets"%>

<div class="bg-dark dk" id="wrap">
	<%= render "admins/top"%>
    <div id="left">
        <div class="media user-media bg-dark dker">
		    <div class="user-media-toggleHover">
		      <span class="fa fa-user"></span>
		    </div>
		    <div class="user-wrapper bg-dark">
		      <a class="user-link" href="">
		          <%= image_tag('user.gif',class: "media-object img-thumbnail user-img")%>
		        <span class="label label-danger user-label"><%= current_admin.sign_in_count%></span>
		      </a>
		      <div class="media-body">
		        <h5 class="media-heading">SUPER ADMIN</h5>
		        <ul class="list-unstyled user-info">
		          <li>ADMIN</li>
		          <li>Last Access : <br>
		            <small><i class="fa fa-calendar"></i>&nbsp;<%= current_admin.last_sign_in_at.strftime("%d %B %t at %I:%M %p")%></small>
		            <%#= link_to "(Edit Profile)" ,edit_user_registration_path%>
		          </li>
		        </ul>
		      </div>
		    </div>
		  </div>
        <!-- #menu -->
        <ul id="menu" class="bg-blue dker">
            <li class="nav-divider"></li>  
            <li class="">
                <%= link_to admins_path do%>
                    <i class="fa fa-dashboard"></i>
                    <span class="link-title">&nbsp;Dashboard</span>
                <%end%>
            </li>
            <li class="active">
                <%= link_to admin_schools_path(current_admin) do%>
                  <i class="fa fa-tasks"></i>
                  <span class="link-title">Schools</span>
                <%end%>
            </li>
            <li class="">
                <%= link_to admin_teachers_path(current_admin) do%>
                  <i class="fa fa-tasks"></i>
                  <span class="link-title">Teachers</span>
                <%end%>
            </li>
            <li class="">
                <%= link_to admin_students_path(current_admin) do%>
                  <i class="fa fa-pencil"></i>
                  <span class="link-title">Students</span>
                <%end%>
            </li>
            <li>
                <%= link_to admin_vendors_path(current_admin) do%>
                  <i class="fa fa-table"></i>
                  <span class="link-title">Vendors</span>
                <%end%>
            </li>
            <li>
                <a href="">
                  <i class="fa fa-font"></i>
                  <span class="link-title">Total Earning</span>
                </a>
            </li>
            <li class="nav-divider"></li>
        </ul>
        <!-- /#menu -->
    </div>
    <!-- /#left -->
    <div id="content">
        <div class="outer">
            <div class="inner bg-light lter">
      			<div>
      				<h3>SCHOOLS</h3>
				    <div class="table-responsive">          
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Contact</th>
                                <th>Status</th>
                              </tr>
                            </thead>
                            <% @schools.each do |school|%>
                                <tbody>
                                  <tr>
                                    <td><%=school.id%></td>
                                    <td><%=school.name%></td>
                                    <td><%=school.email%></td>
                                    <td><%=school.phone_no%></td>
                                    <td>
                                        <%=link_to "Edit",admin_school_update_path(school.id),class: "btn btn-primary btn-xs"%>
                                        <% if school.active? %> <%=link_to "Deactivate",admin_activate_path(school.id), method: :post, data: { confirm: "Do you to want Deactivate School Profile?" }, class: "btn btn-danger btn-xs"%>
                                        <%else%>
                                            <%=link_to "Activate",admin_activate_path(school.id), method: :post, data: { confirm: "Do you to want Activate School Profile?" }, class: "btn btn-success btn-xs"%>
                                        <% end %>
                                        <%=link_to "Upload Video",admin_video_upload_path(school.id),class: "btn btn-primary btn-xs"%>
                                    </td>
                                  </tr>
                                </tbody>
                            <%end%>
                        </table>
                    </div>
    			</div>
				<hr>
            </div>
            <!-- /.inner -->
        </div>
        <!-- /.outer -->
    </div>
    <!-- /#content -->
</div>
<!-- /#wrap -->
<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>
<!-- /#footer -->
<!-- #helpModal -->
<div id="helpModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                    culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
       
<%= render "layouts/javascripts"%>

app/views/admins/students.html.erb
<title>Admin Dashboard</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= render "layouts/stylesheets"%>

<div class="bg-dark dk" id="wrap">
	<%= render "admins/top"%>
    <div id="left">
        <div class="media user-media bg-dark dker">
		    <div class="user-media-toggleHover">
		      <span class="fa fa-user"></span>
		    </div>
		    <div class="user-wrapper bg-dark">
		      <a class="user-link" href="">
		          <%= image_tag('user.gif',class: "media-object img-thumbnail user-img")%>
		        <span class="label label-danger user-label"><%= current_admin.sign_in_count%></span>
		      </a>
		      <div class="media-body">
		        <h5 class="media-heading">SUPER ADMIN</h5>
		        <ul class="list-unstyled user-info">
		          <li>ADMIN</li>
		          <li>Last Access : <br>
		            <small><i class="fa fa-calendar"></i>&nbsp;<%= current_admin.last_sign_in_at.strftime("%d %B %t at %I:%M %p")%></small>
		            <%#= link_to "(Edit Profile)" ,edit_user_registration_path%>
		          </li>
		        </ul>
		      </div>
		    </div>
		  </div>
        <!-- #menu -->
        <ul id="menu" class="bg-blue dker">
            <li class="nav-divider"></li>  
            <li class="">
              <%= link_to admins_path do%>
                  <i class="fa fa-dashboard"></i>
                  <span class="link-title">&nbsp;Dashboard</span>
              <%end%>
            </li>
            <li class="">
                <%= link_to admin_schools_path(current_admin) do%>
                  <i class="fa fa-tasks"></i>
                  <span class="link-title">Schools</span>
                <%end%>
            </li>
            <li class="">
                <%= link_to admin_teachers_path(current_admin) do%>
                  <i class="fa fa-tasks"></i>
                  <span class="link-title">Teachers</span>
                <%end%>
            </li>
            <li class="active">
                <%= link_to admin_students_path(current_admin) do%>
                  <i class="fa fa-pencil"></i>
                  <span class="link-title">Students</span>
                <%end%>
            </li>
            <li>
                <%= link_to admin_vendors_path(current_admin) do%>
                  <i class="fa fa-table"></i>
                  <span class="link-title">Vendors</span>
                <%end%>
            </li>
            <li>
                <a href="">
                  <i class="fa fa-font"></i>
                  <span class="link-title">Total Earning</span>
                </a>
            </li>
            <li class="nav-divider"></li>
        </ul>
        <!-- /#menu -->
    </div>
    <!-- /#left -->
    <div id="content">
        <div class="outer">
            <div class="inner bg-light lter">
      			<div>
      				<h3>STUDENTS</h3>
				    <div class="table-responsive">          
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Contact</th>
                                <th>Status</th>
                              </tr>
                            </thead>
                            <% @students.each do |student|%>
                                <tbody>
                                  <tr>
                                    <td><%=student.id%></td>
                                    <td><%=student.name%></td>
                                    <td><%=student.email%></td>
                                    <td><%=student.phone_no%></td>
                                    <td>
                                     <%=link_to "Edit",admin_school_update_path(student.id),class: "btn btn-primary btn-xs"%>
                                        <% if student.active? %> <%=link_to "Deactivate",admin_activate_path(student.id), method: :post, data: { confirm: "Do you want to Deactivate Student Profile?" }, class: "btn btn-danger btn-xs"%>
                                        <%else%>
                                            <%=link_to "Activate",admin_activate_path(student.id), method: :post, data: { confirm: "Do you want to Activate Student Profile?" }, class: "btn btn-success btn-xs"%>
                                        <% end %>
                                    </td>
                                  </tr>
                                </tbody>
                            <%end%>
                        </table>
                    </div>
    			</div>
				<hr>
            </div>
            <!-- /.inner -->
        </div>
        <!-- /.outer -->
    </div>
    <!-- /#content -->
</div>
<!-- /#wrap -->
<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>
<!-- /#footer -->
<!-- #helpModal -->
<div id="helpModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                    culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
       
<%= render "layouts/javascripts"%>

app/views/admins/teachers.html.erb
<title>Admin Dashboard</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= render "layouts/stylesheets"%>

<div class="bg-dark dk" id="wrap">
	<%= render "admins/top"%>
    <div id="left">
        <div class="media user-media bg-dark dker">
		    <div class="user-media-toggleHover">
		      <span class="fa fa-user"></span>
		    </div>
		    <div class="user-wrapper bg-dark">
		      <a class="user-link" href="">
		          <%= image_tag('user.gif',class: "media-object img-thumbnail user-img")%>
		        <span class="label label-danger user-label"><%= current_admin.sign_in_count%></span>
		      </a>
		      <div class="media-body">
		        <h5 class="media-heading">SUPER ADMIN</h5>
		        <ul class="list-unstyled user-info">
		          <li>ADMIN</li>
		          <li>Last Access : <br>
		            <small><i class="fa fa-calendar"></i>&nbsp;<%= current_admin.last_sign_in_at.strftime("%d %B %t at %I:%M %p")%></small>
		            <%#= link_to "(Edit Profile)" ,edit_user_registration_path%>
		          </li>
		        </ul>
		      </div>
		    </div>
		  </div>
        <!-- #menu -->
        <ul id="menu" class="bg-blue dker">
            <li class="nav-divider"></li>  
            <li class="">
              <%= link_to admins_path do%>
                  <i class="fa fa-dashboard"></i>
                  <span class="link-title">&nbsp;Dashboard</span>
              <%end%>
            </li>
            <li class="">
                <%= link_to admin_schools_path(current_admin) do%>
                  <i class="fa fa-tasks"></i>
                  <span class="link-title">Schools</span>
                <%end%>
            </li>
            <li class="active">
                <%= link_to admin_teachers_path(current_admin) do%>
                  <i class="fa fa-tasks"></i>
                  <span class="link-title">Teachers</span>
                <%end%>
            </li>
            <li class="">
                <%= link_to admin_students_path(current_admin) do%>
                  <i class="fa fa-pencil"></i>
                  <span class="link-title">Students</span>
                <%end%>
            </li>
            <li>
                <%= link_to admin_vendors_path(current_admin) do%>
                  <i class="fa fa-table"></i>
                  <span class="link-title">Vendors</span>
                <%end%>
            </li>
            <li>
                <a href="">
                  <i class="fa fa-font"></i>
                  <span class="link-title">Total Earning</span>
                </a>
            </li>
            <li class="nav-divider"></li>
        </ul>
        <!-- /#menu -->
    </div>
    <!-- /#left -->
    <div id="content">
        <div class="outer">
            <div class="inner bg-light lter">
      			<div>
      				<h3>TEACHERS</h3>
				    <div class="table-responsive">          
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Contact</th>
                                <th>Status</th>
                              </tr>
                            </thead>
                            <% @teachers.each do |teacher|%>
                                <tbody>
                                  <tr>
                                    <td><%=teacher.id%></td>
                                    <td><%=teacher.name%></td>
                                    <td><%=teacher.email%></td>
                                    <td><%=teacher.phone_no%></td>
                                    <td>
                                     <%=link_to "Edit",admin_school_update_path(teacher.id),class: "btn btn-primary btn-xs"%>
                                        <% if teacher.active? %> <%=link_to "Deactivate",admin_activate_path(teacher.id), method: :post, data: { confirm: "Do you want to Deactivate Teacher Profile?" }, class: "btn btn-danger btn-xs"%>
                                        <%else%>
                                            <%=link_to "Activate",admin_activate_path(teacher.id), method: :post, data: { confirm: "Do you want to Activate Teacher Profile?" }, class: "btn btn-success btn-xs"%>
                                        <% end %>
                                        <%=link_to "Upload Video",admin_video_upload_path(teacher.id),class: "btn btn-primary btn-xs"%>
                                    </td>
                                  </tr>
                                </tbody>
                            <%end%>
                        </table>
                    </div>
    			</div>
				<hr>
            </div>
            <!-- /.inner -->
        </div>
        <!-- /.outer -->
    </div>
    <!-- /#content -->
</div>
<!-- /#wrap -->
<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>
<!-- /#footer -->
<!-- #helpModal -->
<div id="helpModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                    culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
       
<%= render "layouts/javascripts"%>

app/views/admins/vendors.html.erb
<title>Admin Dashboard</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= render "layouts/stylesheets"%>

<div class="bg-dark dk" id="wrap">
	<%= render "admins/top"%>
    <div id="left">
        <div class="media user-media bg-dark dker">
		    <div class="user-media-toggleHover">
		      <span class="fa fa-user"></span>
		    </div>
		    <div class="user-wrapper bg-dark">
		      <a class="user-link" href="">
		          <%= image_tag('user.gif',class: "media-object img-thumbnail user-img")%>
		        <span class="label label-danger user-label"><%= current_admin.sign_in_count%></span>
		      </a>
		      <div class="media-body">
		        <h5 class="media-heading">SUPER ADMIN</h5>
		        <ul class="list-unstyled user-info">
		          <li>ADMIN</li>
		          <li>Last Access : <br>
		            <small><i class="fa fa-calendar"></i>&nbsp;<%= current_admin.last_sign_in_at.strftime("%d %B %t at %I:%M %p")%></small>
		            <%#= link_to "(Edit Profile)" ,edit_user_registration_path%>
		          </li>
		        </ul>
		      </div>
		    </div>
		  </div>
        <!-- #menu -->
        <ul id="menu" class="bg-blue dker">
            <li class="nav-divider"></li>  
            <li class="">
              <%= link_to admins_path do%>
                  <i class="fa fa-dashboard"></i>
                  <span class="link-title">&nbsp;Dashboard</span>
              <%end%>
            </li>
            <li class="">
                <%= link_to admin_schools_path(current_admin) do%>
                  <i class="fa fa-tasks"></i>
                  <span class="link-title">Schools</span>
                <%end%>
            </li>
            <li class="">
                <%= link_to admin_teachers_path(current_admin) do%>
                  <i class="fa fa-tasks"></i>
                  <span class="link-title">Teachers</span>
                <%end%>
            </li>
            <li class="">
                <%= link_to admin_students_path(current_admin) do%>
                  <i class="fa fa-pencil"></i>
                  <span class="link-title">Students</span>
                <%end%>
            </li>
            <li class = "active">
                <%= link_to admin_vendors_path(current_admin) do%>
                  <i class="fa fa-table"></i>
                  <span class="link-title">Vendors</span>
                <%end%>
            </li>
            <li>
                <a href="">
                  <i class="fa fa-font"></i>
                  <span class="link-title">Total Earning</span>
                </a>
            </li>
            <li class="nav-divider"></li>
        </ul>
        <!-- /#menu -->
    </div>
    <!-- /#left -->
    <div id="content">
        <div class="outer">
            <div class="inner bg-light lter">
      			<div>
      				<h3>VENDORS</h3>
				    <div class="table-responsive">          
                        <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Contact</th>
                                <th>Status</th>
                              </tr>
                            </thead>
                            <% @vendors.each do |vendor|%>
                                <tbody>
                                  <tr>
                                    <td><%=vendor.id%></td>
                                    <td><%=vendor.name%></td>
                                    <td><%=vendor.email%></td>
                                    <td><%=vendor.phone_no%></td>
                                    <td>
                                     <%=link_to "Edit",admin_school_update_path(vendor.id),class: "btn btn-primary btn-xs"%>
                                        <% if vendor.active? %> <%=link_to "Deactivate",admin_activate_path(vendor.id), method: :post, data: { confirm: "Do you to want Deactivate Vendor Profile?" }, class: "btn btn-danger btn-xs"%>
                                        <%else%>
                                            <%=link_to "Activate",admin_activate_path(vendor.id), method: :post, data: { confirm: "Do you want to Activate Vendor Profile?" }, class: "btn btn-success btn-xs"%>
                                        <% end %>
                                    </td>
                                  </tr>
                                </tbody>
                            <%end%>
                        </table>
                    </div>
    			</div>
				<hr>
            </div>
            <!-- /.inner -->
        </div>
        <!-- /.outer -->
    </div>
    <!-- /#content -->
</div>
<!-- /#wrap -->
<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>
<!-- /#footer -->
<!-- #helpModal -->
<div id="helpModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                    culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
       
<%= render "layouts/javascripts"%>