config/routes.rb
Rails.application.routes.draw do

  
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resource :showcase do 
		collection do 
			get :school_showcase
		end
	end

	resources :students do 
		get :pay_fees_school
		post :pay_fees_school
		get :fee_details
		get :pay_fees_tutor
		post :pay_fees_tutor
		get :sale_book
		post :sale_book 
		get :schools
		get :apply_school
		post :apply_school
		get :teachers
		get :apply_teacher
		post :apply_teacher
		get :slots
	end

	resources :teachers do
		get :schools
		get :students
		get :apply_school
		post :apply_school
		get :find_student
		get :sale_notes
		get :create_sale_notes
		post :create_sale_notes
		get :update_sale_notes
		patch :update_sale_notes
		get :sale
		get :destroy_sale_notes
		get :slots
		get :create_slots
		post :create_slots
		get :update_slots
		patch :update_slots
		get :destroy_slot
		get :demo_videos
		get :create_demo_videos
		post :create_demo_videos
		get :update_demo_videos
		patch :update_demo_videos
		get :destroy_demo_video
		get :teacher_openings
	end

	resources :schools do
		get :teachers
		get :vendors
		get :students
		get :overview
		post :overview
		get :update_overview
		patch :update_overview
		get :courses
		get :course
		post :course
		get :update_course
		patch :update_course
		get :destroy_course
		get :scholarships
		get :scholarship
		post :scholarship
		get :update_scholarship
		patch :update_scholarship
		get :destroy_scholarship
		get :placements
		get :placement
		post :placement
		get :update_placement
		patch :update_placement
		get :destroy_placement
		get :cutoffs
		get :cutoff
		post :cutoff
		get :update_cutoff
		patch :update_cutoff
		get :destroy_cutoff
		get :campus
		get :campu
		post :campu
		get :update_campu
		patch :update_campu
		get :destroy_campu
		get	:schoolinformations
		get  :schoolinformation
		post :schoolinformation
		get :update_schoolinformation
		patch :update_schoolinformation
		get :destroy_schoolinformation
		get :schoolpictures
		get  :schoolpicture
		post :schoolpicture
		get :update_schoolpicture
		patch :update_schoolpicture
		get :destroy_schoolpicture
		get :schoolvideos
		get  :schoolvideo
		post :schoolvideo
		get :update_schoolvideo
		patch :update_schoolvideo
		get :destroy_schoolvideo
		get :post_requirements
		post :teacher_requirement
		post :vendor_requirement
	end

	resources :vendors do
		get :schools
		get :vendor_openings
		get :apply_school
		post :apply_school
	end

	root to: "users#index"
	devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks",
	 sessions: 'users/sessions' ,registrations: 'users/registrations',passwords: 'users/passwords'}
		devise_scope :user do 
			get '/users/login' => 'devise/sessions#new'
		    get '/users/register' => 'devise/registrations#new'
		    get '/users/sign_out' => 'devise/sessions#destroy'
		    #get '/users/:id/showcase' => 'users#showcase'
		end
	devise_for :admins, controllers: { sessions: 'admins/sessions'}
	devise_scope :admin do 
			get '/admins/login' => 'devise/sessions#new'
		    get '/admins/sign_out' => 'devise/sessions#destroy'
		    #get '/users/:id/showcase' => 'users#showcase'
		end
	resources :admins do 
		get :schools
		get :school_update
		patch :school_update
		get :teachers
		get :students
		get :vendors
		post :activate
		get :video_upload
		post :video_upload
	end
	  get 'users/search' 
	  post 'users/search'
	  get 'users/student_show'
	  get 'users/show'
	  get 'users/all_view'
	  post 'users/find_all_course_name'
	  get 'users/current_requirements'
	  get 'users/apply_to_post'
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_school

  def index
    @schools_count = @student.applied_schools.count
    @teachers_count = @student.applied_teachers.count
  end

  def pay_fees_school
    @school_name = User.where(:role => "school")
  	 if request.get?
      @school_fees = PayFee.new
    else
      @school_fees = @student.pay_fees.create(pay_fee_params)
      if @school_fees.save
        redirect_to student_fee_details_path 
      else 
      end
    end 
  end

  def fee_details
  end

  def pay_fees_tutor
    @teacher_name = User.where(:role => "teacher")
     if request.get?
      @teacher_fees = PayFeeToTeacher.new
    else
      @teacher_fees = @student.pay_fee_to_teachers.create(pay_fee_to_teacher_params)
      if @teacher_fees.save
        redirect_to students_path 
      else 
      end
    end 
  end

  def sale_book
     if request.get?
      @sale_book = SellBook.new
    else
      @sale_book = @student.sell_books.create(sale_book_params)
      if @sale_book.save
        redirect_to students_path 
      else 
      end
    end 
  end

  def schools
    @schools = User.where(:role => "school")
    @name = @schools.pluck(:name)
    @city_id = @schools.pluck(:city_id)
    @cities = City.find(@city_id)
    @search = User.where("name = ? AND city_id= ?", params[:name],params[:city_id]) if params[:name] && params[:city_id].present?
  end
  def apply_school
    if request.get?
      @apply_school = AppliedSchool.new
      @school = User.find_by_id(params[:student_id])
    else
      @apply_school = @student.applied_schools.create(apply_school_params)
        if @apply_school.save
            redirect_to student_schools_path
        else 
        end
      end 
  end

  def teachers
    @teachers = User.where(:role => "teacher")
    @name = @teachers.pluck(:name)
    @city_id = @teachers.pluck(:city_id)
    @cities = City.find(@city_id)
    @subjects = @teachers.pluck(:qualification).uniq
    @search = User.where("name = ? AND city_id= ? AND qualification= ?",
      params[:name],params[:city_id],params[:qualification]) if params[:name] && params[:city_id] && params[:qualification].present?
  end
  def apply_teacher
    if request.get?
      @apply_teacher = AppliedTeacher.new
      @teacher = User.find_by_id(params[:student_id])
    else
      @apply_teacher = @student.applied_teachers.create(apply_teacher_params)
        if @apply_teacher.save
            redirect_to student_teachers_path
        else 
        end
      end 
  end

  def slots
    @apply_teacher = AppliedTeacher.new
    @teacher = User.find(params[:student_id])
    @slots = @teacher.slots
  end


  private

  def set_school
      @student = User.find_by_id(current_user)
  end

  def pay_fee_params
  	params.require(:pay_fee).permit(:name,:email,:phone_no,:name_of_school,:user_id,:user_type)
  end

  def pay_fee_to_teacher_params
    params.require(:pay_fee_to_teacher).permit(:name,:email,:phone_no,:teacher_name,:user_id,:user_role)
  end

  def sale_book_params
    params.require(:sell_book).permit(:title,:description,:price,:book,:user_id)
  end

  def apply_school_params
      params.require(:applied_school).permit(:name,:email,:phone_no,:description,:school_id,:user_id,:role)
  end

  def apply_teacher_params
      params.require(:applied_teacher).permit(:name,:email,:phone_no,:description,:teacher_id,:user_id,:user_role)
  end
  
end

app/helpers/students_helper.rb
module StudentsHelper
	
end

app/views/students/_left.html.erb
<div id="left">
	<div class="media user-media bg-dark dker">
		<div class="user-media-toggleHover">
		<span class="fa fa-user"></span>
		</div>
		<div class="user-wrapper bg-dark">
			<a class="user-link" href="">
				<% if current_user.profile_image.present? %>
					<%= image_tag current_user.profile_image,class: "media-object img-thumbnail user-img",:size => "80x80" %>
				<%else%>
					<%= image_tag ("user.png"),class: "media-object img-thumbnail user-img",:size => "80x80" %>
				<%end%>
				<span class="label label-danger user-label"></span>
			</a>
			<div class="media-body">
				<h5 class="media-heading"><%= current_user.name%></h5>
				<ul class="list-unstyled user-info">
					<li><a href=""><%= current_user.role%></a></li>
					<li>Last Access : <br>
						<small><i class="fa fa-calendar"></i>&nbsp;<%= current_user.last_sign_in_at.strftime("%d %B %t at %I %M %p")%></small>
						<% if current_user.active? %>
							<%= link_to "(Edit Profile)" ,edit_user_registration_path%>
						<%else%>
							<a href="#applyModal" data-toggle="modal">(Edit Profile)
							</a>
						<%end%>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- #menu -->
	<ul id="menu" class="bg-blue dker">
		<li class="nav-divider"></li>  
		<li <%if active == 'Dashboard'%> class="active" <%end%>>
			<%= link_to students_path do%>
        		<i class="fa fa-dashboard"></i><span class="link-title">&nbsp;Dashboard</span>
      		<%end%>
		</li>
		<li <%if active == 'Fee'%> class="active" <%end%>>
			<a href="javascript:;">
				<i class="fa fa-building "></i>
				<span class="link-title">Pay Fees</span>
				<span class="fa arrow"></span>
			</a>
			<ul class="collapse">
				<li>
					<% if current_user.active? %>
						<%= link_to student_pay_fees_school_path(@current_user) do%>
							<i class="fa fa-angle-right"></i>&nbsp; For School
						<%end%>
					<%else%>
							<a href="#applyModal" data-toggle="modal" class="fa fa-angle-right">For School</a>
					<%end%>
				</li>
				<li>
					<% if current_user.active? %>
						<%= link_to student_pay_fees_tutor_path(@current_user) do%>
							<i class="fa fa-angle-right"></i>&nbsp;For Tutor
						<%end%>
					<%else%>
						<a href="#applyModal" data-toggle="modal" class="fa fa-angle-right">For Tutor</a>
					<%end%>
				</li>
			</ul>
		</li>
		<li <%if active == 'Book'%> class="active" <%end%>>
			<% if current_user.active? %>
				<%= link_to student_sale_book_path(@current_user) do%>
					<i class="fa fa-tasks"></i>
					<span class="link-title">Sell Book</span>
				<%end%>
			<%else%>
				<a href="#applyModal" data-toggle="modal" class="fa fa-tasks" class="link-title">Sell Book</a>
			<%end%>
		</li>
		<li <%if active == 'Schools'%> class="active" <%end%>>
			<% if current_user.active? %>
				<%= link_to student_schools_path(@current_user) do%>
					<i class="fa fa-tasks"></i>
					<span class="link-title">Apply To School</span>
				<%end%>
			<%else%>
				<a href="#applyModal" data-toggle="modal" class="fa fa-tasks" class="link-title">Apply To School</a>
			<%end%>
		</li>
		<li <%if active == 'Teachers'%> class="active" <%end%>>
			<% if current_user.active? %>
				<%= link_to student_teachers_path(@current_user) do%>
					<i class="fa fa-tasks"></i>
					<span class="link-title">Apply To Teacher</span>
				<%end%>
			<%else%>
				<a href="#applyModal" data-toggle="modal" class="fa fa-tasks" class="link-title">Apply To Teacher</a>
			<%end%>
		</li>
		<li class="">
			<a href="">
				<i class="fa fa-pencil"></i>
				<span class="link-title">
				Buy Book
				</span>
			</a>
		</li>
		<li class="nav-divider"></li>
	</ul>
	<!-- /#menu -->
</div>
<!-- /#left -->

app/views/students/apply_school.html.erb
<title>Apply School</title>
<%= render "layouts/stylesheets"%>

<div class="bg-dark dk" id="wrap">
  <%= render "students/top"%>
  <%= render :partial => "students/left", :locals => { :active => 'School' }%>
  <div id="content">
    <div class="outer">
      <div class="inner bg-light lter">
        <h4><p><font size="3" color="blue"> Hi <%=current_user.name%>, You are applying for <%=@school.name%> </font></p></h4>
        <div class="row vdiocont">    
          <%= form_for @apply_school, url: student_apply_school_path do |f| %>
            <div class="form-group margunrve">
              <label for="email">Name</label>
              <%=f.text_field :name, class: "form-control",value: current_user.name %>
            </div>
            <div class="form-group margunrve">
              <label for="pwd">Email</label>
              <%=f.email_field :email, class: "form-control",value: current_user.email %>
            </div>
            <div class="form-group margunrve">
              <label for="email">Phone No</label>
              <%= f.text_field :phone_no, class: "form-control",value: current_user.phone_no%>
            </div>
            <div class="form-group margunrve">
              <label for="email">Description</label>
              <%= f.text_area :description, class: "form-control"%>
            </div>
            <div class="form-group margunrve text-center">
              <%= f.hidden_field :school_id, value: params[:student_id]%>
              <%= f.hidden_field :role, value: current_user.role%>
              <%=f.submit "Submit", class: "btn btn-default"%>
              <button type="submit" class="btn btn-default">Cancel</button>
            </div>
          <%end%> 
        </div>
      </div>
      <!-- /.inner -->
    </div>
    <!-- /.outer -->
  </div>
  <!-- /#content -->
</div>
<!-- /#wrap -->

<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>
<!-- /#footer -->

<!-- #helpModal -->
<div id="helpModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
          <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
              et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
              aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
              cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
              culpa qui officia deserunt mollit anim id est laborum.
          </p>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
      <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

<%= render "layouts/javascripts"%>

app/views/students/index.html.erb
<title>Student Dashboard</title>
<meta name="viewport" content="width=device-width, initial-scale=1">    

<%= render 'layouts/stylesheets'%>
<div class="bg-dark dk" id="wrap">
	<%= render 'students/top'%>
	<%= render :partial => "students/left", :locals => { :active => 'Dashboard' }%>
	<div id="content">
		<div class="outer">
			<div class="inner bg-light lter">
				<div>
					<h3>Student Dashboard</h3>
					<hr>
					<div class="row">
						<div class="col-md-12 col-sm-12">
							<div class="col-md-3 col-sm-3">
								<% if current_user.active? %>
									<%= link_to student_pay_fees_school_path(@current_user) do%>
										<div class="counting-box" id="encounter">
											<%= image_tag ('Schlogo.png')%>
											<h4 class="count-this">1582</h4>
											<p>Pay Fee For School</p>
										</div>
									<%end%>
								<%else%>
									<a href="#applyModal" data-toggle="modal">
										<div class="counting-box" id="encounter">
											<%= image_tag ('Schlogo.png')%>
											<h4 class="count-this">1582</h4>
											<p>Pay Fee For School</p>
										</div>
									</a>
								<%end%>
							</div>
							<div class="col-md-3 col-sm-3">
								<% if current_user.active? %>
									<%= link_to student_pay_fees_tutor_path(@current_user) do%>
										<div class="counting-box" id="locations">
											<%= image_tag ('tlogo.png')%>
											<h4 class="count-this">312</h4>
											<p>Pay Fee For Tutor</p>
										</div>
									<%end%>
								<%else%>
									<a href="#applyModal" data-toggle="modal">
										<div class="counting-box" id="encounter">
											<%= image_tag ('tlogo.png')%>
											<h4 class="count-this">1582</h4>
											<p>Pay Fee For Tutor</p>
										</div>
									</a>
								<%end%>
							</div>
							<div class="col-md-3 col-sm-3">
								<% if current_user.active? %>
									<%= link_to student_schools_path(@current_user) do%>
										<div class="counting-box" id="encounter">
											<%= image_tag ('Schlogo.png')%>
											<h4 class="count-this"><%=@schools_count%></h4>
											<p>Apply To School</p>
										</div>
									<%end%>
								<%else%>
									<a href="#applyModal" data-toggle="modal">
										<div class="counting-box" id="encounter">
											<%= image_tag ('Schlogo.png')%>
											<h4 class="count-this">1582</h4>
											<p>Apply To School</p>
										</div>
									</a>
								<%end%>
							</div>
							<div class="col-md-3 col-sm-3">
								<% if current_user.active? %>
									<%= link_to student_teachers_path(@current_user) do%>
									<div class="counting-box" id="locations">
										<%= image_tag ('tlogo.png')%>
										<h4 class="count-this"><%=@teachers_count%></h4>
										<p>Apply To Teacher</p>
									</div>
								<%end%>
								<%else%>
									<a href="#applyModal" data-toggle="modal">
										<div class="counting-box" id="encounter">
											<%= image_tag ('tlogo.png')%>
											<h4 class="count-this">1582</h4>
											<p>Apply To Teacher</p>
										</div>
									</a>
								<%end%>
							</div>
						</div>
					</div>
					<hr>
				</div>
			</div>
			<!-- /.inner -->
		</div>
		<!-- /.outer -->
	</div>
	<!-- /#content -->
</div>
<!-- /#wrap -->

<footer class="Footer bg-dark dker">
	<p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>
<!-- /#footer -->
<!-- #helpModal -->
<div id="helpModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Modal title</h4>
			</div>
			<div class="modal-body">
				<p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
				</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>

<%= render 'layouts/javascripts'%>

<div id="applyModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
              <p>
                  Hi <%=current_user.name%>, You Acount Is Deactivated, Please Contact to Admin.
              </p>
          </div>
        </div>
    </div>
</div>

app/views/students/schools.html.erb
<title>Apply School</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= render "layouts/stylesheets"%>

<%= stylesheet_link_tag  "searchbar" %>
<style type="text/css">
  .bigbox {
    border: 1px solid;
    border-radius: 8px;
    margin-bottom: 40px;
    padding: 10px;
  }
  .img-responsive.collglogo {
    width:80px;
  }
  .col-md-12.Anxtysf {
    padding: 20px 0 2px;
    
  }
  .btn.btn-primary.TxtceNtr {
    float: right;
  }
  .paDtpZeRo {
    margin-top: 0 !important;
  } 
</style>  

<div class="bg-dark dk" id="wrap">
  <%= render "students/top"%>
  <%= render :partial => "students/left", :locals => { :active => 'School' }%>
  <div id="content">
    <div class="outer">
      <div class="inner bg-light lter">
        <h3>Apply School</h3>
        <hr>
        <form class="form-wrapper cf">
        <%= form_tag teacher_schools_path(current_user), :method => 'get' do %>
          <%= select_tag "name",options_for_select(@name),prompt: "Select School"%>
          <%= select_tag "city_id",options_for_select(@cities.collect{|p| [p.name, p.id]}),prompt: "Select City"%>
          <%#= select_tag "qualification",options_for_select(@subjects),prompt: "Select Subject"%>
          <%= button_tag "Search" ,:class => "sEarch"%>
        <% end %>
        </form>
        <div class="col-md-12">
          <h3>Schools</h3>
          <% if @search.present?%>
            <% @search.each do |search|%>
              <div class="bigbox">
                <div class="row">
                  <div class="col-md-12">
                    <div class="col-md-2">
                      <% if search.profile_image.present?%>
                        <%= image_tag search.profile_image ,class: "img-thumbnail img-responsive collglogo"%>
                      <%else%>
                        <%= image_tag("img.jpg", class: "img-thumbnail img-responsive collglogo")%>
                      <% end %>
                    </div>
                    <div class="col-md-10">
                    <a href="/users/show?id=<%= search.id %>">
                      <h4><%= search.name %></h4>
                      <span> <i class="fa fa-map-marker"></i> <%= search.address%>,
                        <% if @city = City.find_by_id(search.city_id)%><%= @city.name%><%end%>,
                        <% if @state = Stat.find_by_id(search.state_id)%><%= @state.name%> <%end%>,
                        <% if @country = Countr.find_by_id(search.country_id)%><%= @country.name%> <%end%>
                        </span>
                      </a>
                        <% @id = AppliedSchool.find_by_user_id_and_school_id(current_user, search)%>
                        <%if @id.present?%>
                          <button class="btn btn-primary TxtceNtr" data-toggle="modal" href="#applyModal<%=search.id%>">Apply Now </button>
                        <%else%>
                          <%=link_to "Apply Now",student_apply_school_path(search),class: "btn btn-primary TxtceNtr" %>
                        <%end%>
                    </div>
                    <div id="applyModal<%=search.id%>" class="modal fade">
                      <div class="modal-dialog">
                          <div class="modal-content">
                              <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                  <h4 class="modal-title">School</h4>
                              </div>
                              <div class="modal-body">
                                  <p>
                                      Hi <%=current_user.name%>, You already applied for <%=search.name%>
                                  </p>
                              </div>
                          </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <%end%>
          <%else%>
            <% if @schools.present? %>
              <% @schools.each do |school|%>
                <div class="bigbox">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="col-md-2">
                        <% if school.profile_image.present?%>
                          <%= image_tag school.profile_image ,class: "img-thumbnail img-responsive collglogo"%>
                        <%else%>
                          <%= image_tag("img.jpg", class: "img-thumbnail img-responsive collglogo")%>
                        <% end %>
                      </div>
                      <div class="col-md-10">
                      <a href="/users/show?id=<%= school.id %>">
                        <h4><%= school.name %></h4>
                        <span> <i class="fa fa-map-marker"></i> <%= school.address%>,
                        <% if @city = City.find_by_id(school.city_id)%><%= @city.name%><%end%>,
                        <% if @state = Stat.find_by_id(school.state_id)%><%= @state.name%> <%end%>,
                        <% if @country = Countr.find_by_id(school.country_id)%><%= @country.name%> <%end%>
                        </span>    
                      </a>
                      <% @id = AppliedSchool.find_by_user_id_and_school_id(current_user, school)%>
                          <%if @id.present?%>
                            <button class="btn btn-primary TxtceNtr" data-toggle="modal" href="#applyModal<%=school.id%>">Apply Now </button>
                          <%else%>
                            <%=link_to "Apply Now",student_apply_school_path(school),class: "btn btn-primary TxtceNtr" %>
                      <%end%>
                      </div>
                      <div id="applyModal<%=school.id%>" class="modal fade">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title">School</h4>
                                </div>
                                <div class="modal-body">
                                    <p>
                                        Hi <%=current_user.name%>, You already applied for <%=school.name%>
                                    </p>
                                </div>
                            </div>
                        </div>
                      </div>
                      <!-- <div class="col-md-12 col-sm-12 col-xs-12 Anxtysf">
                        <div class="col-md-3 col-sm-6 col-xs-6">
                          <i class="fa fa-map-marker "></i> <span>Avg Annual Fees</span>
                          <h6>1 lakh</h6>
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs-6">
                          <i class="fa fa-map-marker"></i> <span>Avg Annual Fees</span>
                          <h6>1 lakh</h6>
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs-6">
                          <i class="fa fa-map-marker"></i> <span>Avg Annual Fees</span>
                          <h6>1 lakh</h6>
                        </div>
                        <div class="col-md-3 col-sm-6 col-xs-6">
                          <%#=link_to "Apply Now",teacher_apply_school_path(school),class: "btn btn-primary TxtceNtr" %>
                        </div>
                      </div> -->
                    </div>
                  </div>
                </div>
              <%end%>
            <%else%>
              <div class="bigbox">
                <div class="row">
                  <div class="col-md-12">
                    <div class="col-md-2">
                      <%= image_tag("img.jpg", class: "img-thumbnail img-responsive collglogo")%>
                    </div>
                    <div class="col-md-10">
                      <h4>Indian Institute of Technology (IITB), Mumbai </h4>
                      <span> <i class="fa fa-map-marker"></i> Mumbai,Maharshtra</span>
                    </div>
                    <div class="col-md-12 col-sm-12 col-xs-12 Anxtysf">
                      <div class="col-md-3 col-sm-6 col-xs-6">
                        <i class="fa fa-map-marker "></i> <span>Avg Annual Fees</span>
                        <h6>1 lakh</h6>
                      </div>
                      <div class="col-md-3 col-sm-6 col-xs-6">
                        <i class="fa fa-map-marker"></i> <span>Avg Annual Fees</span>
                        <h6>1 lakh</h6>
                      </div>
                      <div class="col-md-3 col-sm-6 col-xs-6">
                        <i class="fa fa-map-marker"></i> <span>Avg Annual Fees</span>
                        <h6>1 lakh</h6>
                      </div>
                      <div class="col-md-3 col-sm-6 col-xs-6">
                        <button class="btn btn-primary TxtceNtr">Apply Now </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <%end%>
          <%end%>
        </div>
        <hr>
      </div>
      <!-- /.inner -->
    </div>
    <!-- /.outer -->
  </div>
  <!-- /#content -->
</div>
<!-- /#wrap -->

<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>
<!-- /#footer -->

<!-- #helpModal -->
<div id="helpModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                    culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<%= render "layouts/javascripts"%>