config/routes.rb
Rails.application.routes.draw do

  
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resource :showcase do 
		collection do 
			get :school_showcase
		end
	end

	resources :students do 
		get :pay_fees_school
		post :pay_fees_school
		get :fee_details
		get :pay_fees_tutor
		post :pay_fees_tutor
		get :sale_book
		post :sale_book 
		get :schools
		get :apply_school
		post :apply_school
		get :teachers
		get :apply_teacher
		post :apply_teacher
		get :slots
	end

	resources :teachers do
		get :schools
		get :students
		get :apply_school
		post :apply_school
		get :find_student
		get :sale_notes
		get :create_sale_notes
		post :create_sale_notes
		get :update_sale_notes
		patch :update_sale_notes
		get :sale
		get :destroy_sale_notes
		get :slots
		get :create_slots
		post :create_slots
		get :update_slots
		patch :update_slots
		get :destroy_slot
		get :demo_videos
		get :create_demo_videos
		post :create_demo_videos
		get :update_demo_videos
		patch :update_demo_videos
		get :destroy_demo_video
		get :teacher_openings
	end

	resources :schools do
		get :teachers
		get :vendors
		get :students
		get :overview
		post :overview
		get :update_overview
		patch :update_overview
		get :courses
		get :course
		post :course
		get :update_course
		patch :update_course
		get :destroy_course
		get :scholarships
		get :scholarship
		post :scholarship
		get :update_scholarship
		patch :update_scholarship
		get :destroy_scholarship
		get :placements
		get :placement
		post :placement
		get :update_placement
		patch :update_placement
		get :destroy_placement
		get :cutoffs
		get :cutoff
		post :cutoff
		get :update_cutoff
		patch :update_cutoff
		get :destroy_cutoff
		get :campus
		get :campu
		post :campu
		get :update_campu
		patch :update_campu
		get :destroy_campu
		get	:schoolinformations
		get  :schoolinformation
		post :schoolinformation
		get :update_schoolinformation
		patch :update_schoolinformation
		get :destroy_schoolinformation
		get :schoolpictures
		get  :schoolpicture
		post :schoolpicture
		get :update_schoolpicture
		patch :update_schoolpicture
		get :destroy_schoolpicture
		get :schoolvideos
		get  :schoolvideo
		post :schoolvideo
		get :update_schoolvideo
		patch :update_schoolvideo
		get :destroy_schoolvideo
		get :post_requirements
		post :teacher_requirement
		post :vendor_requirement
	end

	resources :vendors do
		get :schools
		get :vendor_openings
		get :apply_school
		post :apply_school
	end

	root to: "users#index"
	devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks",
	 sessions: 'users/sessions' ,registrations: 'users/registrations',passwords: 'users/passwords'}
		devise_scope :user do 
			get '/users/login' => 'devise/sessions#new'
		    get '/users/register' => 'devise/registrations#new'
		    get '/users/sign_out' => 'devise/sessions#destroy'
		    #get '/users/:id/showcase' => 'users#showcase'
		end
	devise_for :admins, controllers: { sessions: 'admins/sessions'}
	devise_scope :admin do 
			get '/admins/login' => 'devise/sessions#new'
		    get '/admins/sign_out' => 'devise/sessions#destroy'
		    #get '/users/:id/showcase' => 'users#showcase'
		end
	resources :admins do 
		get :schools
		get :school_update
		patch :school_update
		get :teachers
		get :students
		get :vendors
		post :activate
		get :video_upload
		post :video_upload
	end
	  get 'users/search' 
	  post 'users/search'
	  get 'users/student_show'
	  get 'users/show'
	  get 'users/all_view'
	  post 'users/find_all_course_name'
	  get 'users/current_requirements'
	  get 'users/apply_to_post'
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
 before_action :set_teacher, only:[:index,:schools,:apply_school,:find_student,:sale_notes,:create_sale_notes,
 :update_sale_notes,:students,:slots,:create_slots,:update_slots,:demo_videos,:create_demo_videos,:update_demo_videos,
 :teacher_openings]
	
 before_action :check_user_signed_in

	def index
		@schools_count = @teacher.applied_schools.count
		@students_count = AppliedTeacher.where("teacher_id = ? AND user_role= ?",@teacher,"student").count
	end

	def schools
		@schools = User.where(:role => "school")
	    @name = @schools.pluck(:name)
	    @city_id = @schools.pluck(:city_id)
	    @cities = City.find(@city_id)
	    @search = User.where("name = ? AND city_id= ?", params[:name],params[:city_id]) if params[:name] && params[:city_id].present?
	end
	def apply_school
		if request.get?
			@apply_school = AppliedSchool.new
			@school = TeacherRequire.find_by_id(params[:teacher_id])
		else
			@apply_school = @teacher.applied_schools.create(apply_school_params)
		    if @apply_school.save
		        redirect_to teacher_schools_path
		    else 
		    end
    	end 
	end

	def find_student
		@students = User.where(:role => "student")
		@name = @students.pluck(:name)
		@qualification = @students.pluck(:qualification).uniq
	    @city_id = @students.pluck(:city_id)
	    @cities = City.find(@city_id)
	    @search = User.where("name = ? AND qualification = ? AND city_id= ?", params[:name],params[:qualification],params[:city_id]) if params[:name] && params[:city_id].present?
	end

	def sale_notes
		@sale_notes = @teacher.sale_notes
	end
	def create_sale_notes
		if request.get?
			@sale_notes = SaleNote.new
		else
			@sale_notes = @teacher.sale_notes.create(sale_notes_params)
		    if @sale_notes.save
		        redirect_to teacher_sale_notes_path
		    else 
		    end
    	end 
	end
	def update_sale_notes
	    if request.get?
	      @sale_notes = SaleNote.find(params[:teacher_id])
	    else
	      @sale_notes = SaleNote.find(params[:teacher_id])
	      if @sale_notes.update(sale_notes_params)
	        redirect_to teacher_sale_notes_path
	      else
	      end
	    end
  	end
  	def sale
	    @sale_notes = SaleNote.find(params[:teacher_id])
	    if @sale_notes.sale == true
	       @sale_notes.update(sale: false)
	       redirect_to teacher_sale_notes_path
	    else @sale_notes.sale == false
	       @sale_notes.update(sale: true)
	       redirect_to teacher_sale_notes_path
	    end
  	end
  	def destroy_sale_notes
	    @sale_notes = SaleNote.find(params[:teacher_id])
	    if @sale_notes.destroy
	      redirect_to teacher_sale_notes_path
	    else
	    end
  	end

  	def slots
  		@slots = @teacher.slots
  	end
  	def create_slots
  		if request.get?
  			@slots = Slot.new
  		else
	  		@slots = @teacher.slots.create(slot_params)
	  		if @slots.save
	  			redirect_to teacher_slots_path
	  		else
	  		end
	  	end
  	end
  	def update_slots
	    if request.get?
	      @slots = Slot.find(params[:teacher_id])
	    else
	      @slots = Slot.find(params[:teacher_id])
	      if @slots.update(slot_params)
	        redirect_to teacher_slots_path
	      else
	      end
	    end
  	end
  	def destroy_slot
	    @slot = Slot.find(params[:teacher_id])
	    if @slot.destroy
	      redirect_to teacher_slots_path
	    else
	    end
  	end

  	def demo_videos
  		@demo_videos = @teacher.demo_videos
  	end
  	def create_demo_videos
  		if request.get?
  			@demo_video = DemoVideo.new
  		else
	  		@demo_video = @teacher.demo_videos.create(demo_video_params)
	  		if @demo_video.save
	  			redirect_to teacher_demo_videos_path
	  		else
	  		end
	  	end
  	end
  	def update_demo_videos
	    if request.get?
	      @demo_video = DemoVideo.find(params[:teacher_id])
	    else
	      @demo_video = DemoVideo.find(params[:teacher_id])
	      if @demo_video.update(demo_video_params)
	        redirect_to teacher_demo_videos_path
	      else
	      end
	    end
  	end
  	def destroy_demo_video
	    @demo_video = DemoVideo.find(params[:teacher_id])
	    if @demo_video.destroy
	      redirect_to teacher_demo_videos_path
	    else
	    end
  	end

  	def teacher_openings
  		@school = User.find(params[:teacher_id])
  		@teachers = @school.teacher_requires
  	end

  	def students
  		@slots = @teacher.slots
  	end

	private

	def set_teacher
	    @teacher = User.find_by_id(current_user)
	end

	def sale_notes_params
    	params.require(:sale_note).permit(:title,:description,:document,:user_id)
  	end

  	def apply_school_params
    	params.require(:applied_school).permit(:name,:email,:phone_no,:description,:school_id,:user_id,:role)
  	end

  	def slot_params
    	params.require(:slot).permit(:name,:date,:time,:duration,:user_id)
  	end

  	def demo_video_params
    	params.require(:demo_video).permit(:title,:description,:video,:user_id,:user_role)
  	end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_left.html.erb
<div id="left">
  <div class="media user-media bg-dark dker">
    <div class="user-media-toggleHover">
        <span class="fa fa-user"></span>
    </div>
    <div class="user-wrapper bg-dark">
      <a class="user-link" href="">
        <%if current_user.profile_image.present? %>
          <%= image_tag current_user.profile_image,class: "media-object img-thumbnail user-img",:size => "80x80" %>
        <%else%>
          <%= image_tag('user.gif', class: "media-object img-thumbnail user-img")%>
        <%end%>
        <span class="label label-danger user-label"><%= current_user.sign_in_count%></span>
      </a>
      <div class="media-body">
        <h5 class="media-heading"><%= current_user.name%></h5>
        <ul class="list-unstyled user-info">
          <li><%= current_user.role%></li>
          <li>Last Access : <br>
            <small><i class="fa fa-calendar"></i>&nbsp;<%= current_user.last_sign_in_at.strftime("%d %B %t at %I:%M %p")%></small>
            <% if current_user.active? %>
              <%= link_to "(Edit Profile)" ,edit_user_registration_path%>
            <%else%>
              <a href="#applyModal" data-toggle="modal">(Edit Profile)
              </a>
            <%end%>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <!-- #menu -->
  <ul id="menu" class="bg-blue dker">
    <li class="nav-divider"></li>  
      <li <%if active == 'Dashboard'%> class="active" <%end%>>
        <%=link_to teachers_path(@teacher) do%>
          <i class="fa fa-dashboard"></i><span class="link-title">&nbsp;Dashboard</span>
        <%end%>
      </li>
    <li <%if active == 'Apply School'%> class="active" <%end%>>
      <% if current_user.active? %>
        <%=link_to teacher_schools_path(@teacher) do%>
          <i class="fa fa-tasks"></i>
          <span class="link-title">Apply School</span>
        <%end%>
      <%else%>
          <a href="#applyModal" data-toggle="modal" class="fa fa-tasks" class="link-title">Apply School</a>
      <%end%>
    </li>
    <li <%if active == 'Search Student'%> class="active" <%end%>>
      <% if current_user.active? %>
        <%=link_to teacher_find_student_path(@teacher) do%>
          <i class="fa fa-pencil"></i>
          <span class="link-title">Search Student</span>
        <%end%>
      <%else%>
          <a href="#applyModal" data-toggle="modal" class="fa fa-tasks" class="link-title">Search Student</a>
      <%end%>
    </li>
    <li <%if active == 'Sell Notes'%> class="active" <%end%> >
      <% if current_user.active? %>
        <%=link_to teacher_sale_notes_path(@teacher) do%>
          <i class="fa fa-table"></i>
          <span class="link-title">Sell Notes</span>
        <%end%>
      <%else%>
          <a href="#applyModal" data-toggle="modal" class="fa fa-tasks" class="link-title">Sell Notes</a>
      <%end%>
    </li>
    <li <%if active == 'From Students'%> class="active" <%end%> >
      <% if current_user.active? %>
        <%=link_to teacher_students_path(@teacher) do%>
          <i class="fa fa-table"></i>
          <span class="link-title">From Students</span>
        <%end%>
      <%else%>
          <a href="#applyModal" data-toggle="modal" class="fa fa-tasks" class="link-title">From Students</a>
      <%end%>
    </li>
    <li <%if active == 'Slots'%> class="active" <%end%> >
      <% if current_user.active? %>
        <%=link_to teacher_slots_path(@teacher) do%>
          <i class="fa fa-table"></i>
          <span class="link-title">Create Slots</span>
        <%end%>
      <%else%>
          <a href="#applyModal" data-toggle="modal" class="fa fa-tasks" class="link-title">Create Slots</a>
      <%end%>
    </li>
    <li <%if active == 'Videos'%> class="active" <%end%> >
      <% if current_user.active? %>
        <%=link_to teacher_demo_videos_path(@teacher) do%>
          <i class="fa fa-table"></i>
          <span class="link-title">Demo Videos</span>
        <%end%>
      <%else%>
          <a href="#applyModal" data-toggle="modal" class="fa fa-tasks" class="link-title">Demo Videos</a>
      <%end%>
    </li>
    <li>
      <% if current_user.active? %>
        <a href="">
          <i class="fa fa-font"></i>
          <span class="link-title">Total Earning</span>
        </a>
      <%else%>
          <a href="#applyModal" data-toggle="modal" class="fa fa-tasks" class="link-title">Total Earning</a>
      <%end%>
    </li>
    <li class="nav-divider"></li>
  </ul>
  <!-- /#menu -->
</div>
<!-- /#left -->

app/views/teachers/_top.html.erb
<div id="top">
    <!-- .navbar -->
    <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <header class="navbar-header">
               <%= link_to image_tag('logoedu.png',class: "img-responsive DashLogo"), teachers_path, class: "navbar-brand" %>
            </header>
            <div class="topnav">
                <div class="btn-group">
                    <a data-toggle="modal" data-original-title="Help" data-placement="bottom"
                       class="btn btn-default btn-sm"
                       href="#helpModal">
                        <i class="fa fa-question"></i>
                    </a>
                </div>
                <div class="btn-group">
                    <%= link_to "",destroy_user_session_path,class: "btn btn-metis-1 btn-sm fa fa-power-off",data: { confirm: "Do you to want to Logout?" } %>
                </div>
                <div class="btn-group">
                    <a data-placement="bottom" data-original-title="Show / Hide Left" data-toggle="tooltip"
                       class="btn btn-primary btn-sm toggle-left" id="menu-toggle">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
            </div>
        </div>
        <!-- /.container-fluid -->
    </nav>
    <!-- /.navbar -->
</div>
<!-- /#top -->

app/views/teachers/apply_school.html.erb
<title>Apply School</title>
<%= render "layouts/stylesheets"%>

<div class="bg-dark dk" id="wrap">
  <%= render "teachers/top"%>
  <%= render :partial => "teachers/left", :locals => { :active => 'Apply School' }%>
  <div id="content">
    <div class="outer">
      <div class="inner bg-light lter">
        <h4><p><font size="3" color="blue"> Hi <%=current_user.name%>, You are applying for <%=@school.subject%> </font></p></h4>
        <div class="row vdiocont">    
          <%= form_for @apply_school, url: teacher_apply_school_path do |f| %>
            <div class="form-group margunrve">
              <label for="email">Name</label>
              <%=f.text_field :name, class: "form-control",value: current_user.name %>
            </div>
            <div class="form-group margunrve">
              <label for="pwd">Email</label>
              <%=f.email_field :email, class: "form-control",value: current_user.email %>
            </div>
            <div class="form-group margunrve">
              <label for="email">Phone No</label>
              <%= f.text_field :phone_no, class: "form-control",value: current_user.phone_no%>
            </div>
            <div class="form-group margunrve">
              <label for="email">Description</label>
              <%= f.text_area :description, class: "form-control"%>
            </div>
            <div class="form-group margunrve text-center">
              <%= f.hidden_field :school_id, value: params[:teacher_id]%>
              <%= f.hidden_field :role, value: current_user.role%>
              <%=f.submit "Submit", class: "btn btn-default"%>
              <button type="submit" class="btn btn-default">Cancel</button>
            </div>
          <%end%> 
        </div>
      </div>
      <!-- /.inner -->
    </div>
    <!-- /.outer -->
  </div>
  <!-- /#content -->
</div>
<!-- /#wrap -->

<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>
<!-- /#footer -->

<!-- #helpModal -->
<div id="helpModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
          <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
              et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
              aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
              cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
              culpa qui officia deserunt mollit anim id est laborum.
          </p>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
      <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

<%= render "layouts/javascripts"%>

app/views/teachers/demo_videos.html.erb
<title>Teachers</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= render "layouts/stylesheets"%>


<div class="bg-dark dk" id="wrap">
  <%= render "teachers/top"%>
  <%= render :partial => "teachers/left", :locals => { :active => 'Videos' }%>
  <div id="content">
    <div class="outer">
      <div class="inner bg-light lter">
        <h4>Generated Demo Videos</h4> 
        <div class="ADDcorsen text-right">
          <%=link_to "Back",teachers_path, class: "btn btn-primary"%>
          <%=link_to "Add Demo Video",teacher_create_demo_videos_path,class: "btn btn-primary"%>
        </div> 
        <div class="table-responsive ">          
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Action</th>
              </tr>
            </thead>
            <% @demo_videos.each do |video|%>
              <tbody>
                <tr>
                  <td><%=video.title%></td>
                  <td><%=video.description%></td>
                  <td>
                    <%=link_to "Edit",teacher_update_demo_videos_path(video),class: "btn btn-primary btn-xs"%>
                    <%=link_to "Delete",teacher_destroy_demo_video_path(video),class: "btn btn-danger btn-xs", data: { confirm: "Do you to want to Delete?" }%>
                  </td>
                </tr>
              </tbody>
            <%end%>
          </table>
        </div>  
      </div>
      <!-- /.inner -->
    </div>
    <!-- /.outer -->
  </div>
  <!-- /#content -->
</div>
<!-- /#wrap -->

<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>
<!-- /#footer -->
<!-- #helpModal -->
<div id="helpModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
          <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
              et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
              aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
              cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
              culpa qui officia deserunt mollit anim id est laborum.
          </p>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

<%= render "layouts/javascripts"%>

app/views/teachers/sale_notes.html.erb
<title>Sell Notes</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= render "layouts/stylesheets"%>

<div class="bg-dark dk" id="wrap">
  <%= render "teachers/top"%>
  <%= render :partial => "teachers/left", :locals => { :active => 'Sell Notes' }%>
  <div id="content">
    <div class="outer">
      <div class="inner bg-light lter">
        <h4>List of Notes</h4>
        <hr>
        <div class="ADDcorsen text-right">
          <%=link_to "Back",teachers_path, class: "btn btn-primary"%>
          <%=link_to "Add Notes",teacher_create_sale_notes_path(current_user), class: "btn btn-primary"%>
        </div> <br>
        <div class="table-responsive"> 
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Title</th>
                <th>Descrption</th>
                <th>Document</th>
                <th>Action</th>
              </tr>
            </thead>
            <% @sale_notes.each do |notes|%>
              <tbody>
                <tr>
                  <td><%= notes.title%></td>
                  <td><%= notes.description%></td>
                  <% if notes.document_content_type == "application/pdf" or "application/msword" %>
                     <td> <%= link_to (image_tag "doc.png"),notes.document.url(),class: "Textwh text-center", target: '_blank' %><p>Click to view</p></td>
                    <% elsif notes.document_content_type == "image/jpeg" or "image/png" %>
                    <td> <%= link_to (image_tag "dis_image.jpg"),notes.document.url(),class: "Textwh", target: '_blank' %></td>
                    <% end %>
                  <td>



                    <%=link_to "Edit",teacher_update_sale_notes_path(notes),class: "btn btn-primary btn-xs"%>
                    <% if notes.sale == true%>
                      <%=link_to "UnSale",teacher_sale_path(notes), class: "btn btn-danger btn-xs",:confirm => "Do you want to UnSale?"%>
                    <% else notes.sale == false %> 
                      <%=link_to "Sale",teacher_sale_path(notes), class: "btn btn-success btn-xs"%>
                    <% end %>
                    <%=link_to "Delete",teacher_destroy_sale_notes_path(notes),class: "btn btn-danger btn-xs", :confirm => "Are you sure you want to delete?"%>
                  </td>
                </tr>
              </tbody>
            <%end%>
          </table>
        </div>
      </div>
      <!-- /.inner -->
    </div>
    <!-- /.outer -->
  </div>
  <!-- /#content -->
</div>
<!-- /#wrap -->

<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>
<!-- /#footer -->

<!-- #helpModal -->
<div id="helpModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
          <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
              et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
              aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
              cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
              culpa qui officia deserunt mollit anim id est laborum.
          </p>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
      <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>



<%= render "layouts/javascripts" %>

<script language="javascript" type="text/javascript">
  $(document).ready(function() {
    $('#trigger').click(function(){
      $("#dialog").dialog();
    }); 
  });                  
</script>

app/views/teachers/slots.html.erb
<title>Teachers</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= render "layouts/stylesheets"%>


<div class="bg-dark dk" id="wrap">
  <%= render "teachers/top"%>
  <%= render :partial => "teachers/left", :locals => { :active => 'Slots' }%>
  <div id="content">
    <div class="outer">
      <div class="inner bg-light lter">
        <h4>Generated Slots</h4> 
        <div class="ADDcorsen text-right">
          <%=link_to "Back",teachers_path, class: "btn btn-primary"%>
          <%=link_to "Add Slots",teacher_create_slots_path,class: "btn btn-primary"%>
        </div> 
        <div class="table-responsive ">          
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Date</th>
                <th>Time</th>
                <th>Duration</th>
                <th>Action</th>
              </tr>
            </thead>
            <% @slots.each do |slot|%>
              <tbody>
                <tr>
                  <td><%=slot.name%></td>
                  <td><%=slot.date%></td>
                  <td><%=slot.time%></td>
                  <td><%=slot.duration%></td>
                  <td>
                    <%=link_to "Edit",teacher_update_slots_path(slot),class: "btn btn-primary btn-xs"%>
                    <%=link_to "Delete",teacher_destroy_slot_path(slot),class: "btn btn-danger btn-xs", data: { confirm: "Do you to want to Delete?" }%>
                  </td>
                </tr>
              </tbody>
            <%end%>
          </table>
        </div>  
      </div>
      <!-- /.inner -->
    </div>
    <!-- /.outer -->
  </div>
  <!-- /#content -->
</div>
<!-- /#wrap -->

<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>
<!-- /#footer -->
<!-- #helpModal -->
<div id="helpModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
          <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
              et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
              aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
              cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
              culpa qui officia deserunt mollit anim id est laborum.
          </p>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

<%= render "layouts/javascripts"%>