config/routes.rb
Rails.application.routes.draw do

  
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resource :showcase do 
		collection do 
			get :school_showcase
		end
	end

	resources :students do 
		get :pay_fees_school
		post :pay_fees_school
		get :fee_details
		get :pay_fees_tutor
		post :pay_fees_tutor
		get :sale_book
		post :sale_book 
		get :schools
		get :apply_school
		post :apply_school
		get :teachers
		get :apply_teacher
		post :apply_teacher
		get :slots
	end

	resources :teachers do
		get :schools
		get :students
		get :apply_school
		post :apply_school
		get :find_student
		get :sale_notes
		get :create_sale_notes
		post :create_sale_notes
		get :update_sale_notes
		patch :update_sale_notes
		get :sale
		get :destroy_sale_notes
		get :slots
		get :create_slots
		post :create_slots
		get :update_slots
		patch :update_slots
		get :destroy_slot
		get :demo_videos
		get :create_demo_videos
		post :create_demo_videos
		get :update_demo_videos
		patch :update_demo_videos
		get :destroy_demo_video
		get :teacher_openings
	end

	resources :schools do
		get :teachers
		get :vendors
		get :students
		get :overview
		post :overview
		get :update_overview
		patch :update_overview
		get :courses
		get :course
		post :course
		get :update_course
		patch :update_course
		get :destroy_course
		get :scholarships
		get :scholarship
		post :scholarship
		get :update_scholarship
		patch :update_scholarship
		get :destroy_scholarship
		get :placements
		get :placement
		post :placement
		get :update_placement
		patch :update_placement
		get :destroy_placement
		get :cutoffs
		get :cutoff
		post :cutoff
		get :update_cutoff
		patch :update_cutoff
		get :destroy_cutoff
		get :campus
		get :campu
		post :campu
		get :update_campu
		patch :update_campu
		get :destroy_campu
		get	:schoolinformations
		get  :schoolinformation
		post :schoolinformation
		get :update_schoolinformation
		patch :update_schoolinformation
		get :destroy_schoolinformation
		get :schoolpictures
		get  :schoolpicture
		post :schoolpicture
		get :update_schoolpicture
		patch :update_schoolpicture
		get :destroy_schoolpicture
		get :schoolvideos
		get  :schoolvideo
		post :schoolvideo
		get :update_schoolvideo
		patch :update_schoolvideo
		get :destroy_schoolvideo
		get :post_requirements
		post :teacher_requirement
		post :vendor_requirement
	end

	resources :vendors do
		get :schools
		get :vendor_openings
		get :apply_school
		post :apply_school
	end

	root to: "users#index"
	devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks",
	 sessions: 'users/sessions' ,registrations: 'users/registrations',passwords: 'users/passwords'}
		devise_scope :user do 
			get '/users/login' => 'devise/sessions#new'
		    get '/users/register' => 'devise/registrations#new'
		    get '/users/sign_out' => 'devise/sessions#destroy'
		    #get '/users/:id/showcase' => 'users#showcase'
		end
	devise_for :admins, controllers: { sessions: 'admins/sessions'}
	devise_scope :admin do 
			get '/admins/login' => 'devise/sessions#new'
		    get '/admins/sign_out' => 'devise/sessions#destroy'
		    #get '/users/:id/showcase' => 'users#showcase'
		end
	resources :admins do 
		get :schools
		get :school_update
		patch :school_update
		get :teachers
		get :students
		get :vendors
		post :activate
		get :video_upload
		post :video_upload
	end
	  get 'users/search' 
	  post 'users/search'
	  get 'users/student_show'
	  get 'users/show'
	  get 'users/all_view'
	  post 'users/find_all_course_name'
	  get 'users/current_requirements'
	  get 'users/apply_to_post'
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
before_action :set_school, only:[:overview,:update_overview,:courses,:update_course, :course,
  :scholarship,:scholarships,:update_scholarship,:placements,:update_placement,:placement,
  :cutoffs, :cutoff,:update_cuttoff,:campus,:campu,:update_campu,:schoolinformations,:schoolinformation,
  :update_schoolinformation,:schoolpictures,:schoolpicture,:update_schoolpicture,:schoolvideos,
  :schoolvideo,:update_schoolvideo,:teachers,:vendors,:students,:teacher_requirement,:vendor_requirement]

 before_action :check_user_signed_in
  def index
    @course_count = Course.where("user_id = ?",set_school).count
    @scholar_count = Scholarship.where("user_id = ?",set_school).count
    @placement_count = Placement.where("user_id = ?",set_school).count
    @cutoff_count = Cutoff.where("user_id = ?",set_school).count
    @campus_count = Campu.where("user_id = ?",set_school).count
    @news_count = SchoolInformation.where("user_id = ?",set_school).count
    @picture_count = SchoolPicture.where("user_id = ?",set_school).count
    @video_count = SchoolVideo.where("user_id = ?",set_school).count
    @teachers_count = AppliedSchool.where("school_id = ? AND role= ?",@school,"teacher").count
    @vendors_count = AppliedSchool.where("school_id = ? AND role= ?",@school,"vendor").count
    @students_count = AppliedSchool.where("school_id = ? AND role= ?",@school,"student").count
  end

  def teachers
    @teacher_requirements = @school.teacher_requires
  end
  def vendors
    @vendor_requirements = @school.vendor_requires
  end
  def students
    @students = AppliedSchool.where("school_id = ? AND role= ?",@school,"student")
  end

  def overview
    if request.get?
      @overview = Overview.new
    else
      @overview = @school.overviews.create(overview_params)
      if @overview.save
        redirect_to schools_path
      else 
      end
    end 
  end

  def update_overview
    if request.get?
      @id = @school.overviews.first
      @overview = Overview.find_by_id(@id)
    else
      if @school.overviews.update(overview_params)
        redirect_to schools_path
      else 
      end
    end
  end

  def courses
    @courses = @school.courses
  end
  def course
    if request.get?
      @course = Course.new
    else
      @course = @school.courses.create(course_params)
      @course.degree_name = params[:new_degree_name] unless params[:new_degree_name].empty?
      @course.course_name = params[:new_course_name] unless params[:new_course_name].empty?
      if @course.save
        redirect_to school_courses_path
      else 
      end
    end 
  end
  def update_course
    if request.get?
      @course = Course.find(params[:school_id])
    else
      @course = Course.find(params[:school_id])
      @course.degree_name = params[:new_degree_name] unless params[:new_degree_name].empty?
      @course.course_name = params[:new_course_name] unless params[:new_course_name].empty?
      if @course.update(course_params)
        redirect_to school_courses_path
      else
      end
    end
  end
  def destroy_course
    @course = Course.find(params[:school_id])
    if @course.delete
      redirect_to school_courses_path
    else
    end
  end

  def scholarships
    @scholars = @school.scholarships
  end
  def scholarship
    if request.get?
      @scholar = Scholarship.new
    else
      @scholar = @school.scholarships.create(scholar_params)
        if @scholar.save
          redirect_to school_scholarships_path
        else 
        end
    end 
  end
  def update_scholarship
    if request.get?
      @scholar = Scholarship.find(params[:school_id])
    else
      @scholar = Scholarship.find(params[:school_id])
      if @scholar.update(scholar_params)
        redirect_to school_scholarships_path
      else
      end
    end
  end
  def destroy_scholarship
    @scholar = Scholarship.find(params[:school_id])
    if @scholar.destroy
      redirect_to school_scholarships_path
    else
    end
  end

  def placements
    @placements = @school.placements
  end
  def placement
    if request.get?
      @placement = Placement.new
    else
      @placement = @school.placements.create(placement_params)
        if @placement.save
          redirect_to school_placements_path,notice: 'Placement details saved successfully'
        else 
        end
    end 
  end
  def update_placement
    if request.get?
      @placement = Placement.find(params[:school_id])
    else
      @placement = Placement.find(params[:school_id])
      if @placement.update(placement_params)
        redirect_to school_placements_path
      else
      end
    end
  end
  def destroy_placement
    @placement = Placement.find(params[:school_id])
    if @placement.destroy
      redirect_to school_placements_path
    else
    end
  end

  def cutoffs
    @cutoffs = @school.cutoffs
  end
  def cutoff
    if request.get?
      @cutoff = Cutoff.new
    else
      @cutoff = @school.cutoffs.create(cutoff_params)
        if @cutoff.save
          redirect_to school_cutoffs_path
        else 
        end
    end 
  end
  def update_cutoff
    if request.get?
      @cutoff = Cutoff.find(params[:school_id])
    else
      @cutoff = Cutoff.find(params[:school_id])
      if @cutoff.update(cutoff_params)
        redirect_to school_cutoffs_path
      else
      end
    end
  end
  def destroy_cutoff
    @cutoff = Cutoff.find(params[:school_id])
    if @cutoff.destroy
      redirect_to school_cutoffs_path
    else
    end
  end

  def campus
    @campus = @school.campus
  end
  def campu
    if request.get?
      @campu = Campu.new
    else
      @campu = @school.campus.create(campu_params)
        if @campu.save
          redirect_to school_campus_path
        else 
        end
    end 
  end
  def update_campu
    if request.get?
      @campu = Campu.find(params[:school_id])
    else
      @campu = Campu.find(params[:school_id])
      if @campu.update(campu_params)
        redirect_to school_campus_path
      else
      end
    end
  end
  def destroy_campu
    @campu = Campu.find(params[:school_id])
    if @campu.destroy
      redirect_to school_campus_path
    else
    end
  end

  def schoolinformations
    @news = @school.school_informations
  end
  def schoolinformation
    if request.get?
      @news = SchoolInformation.new
    else
      @news = @school.school_informations.create(news_params)
        if @news.save
          redirect_to school_schoolinformations_path
        else 
        end
    end 
  end
  def update_schoolinformation
    if request.get?
      @news = SchoolInformation.find(params[:school_id])
    else
      @news = SchoolInformation.find(params[:school_id])
      if @news.update(news_params)
        redirect_to school_schoolinformations_path
      else
      end
    end
  end
  def destroy_schoolinformation
    @news = SchoolInformation.find(params[:school_id])
    if @news.destroy
      redirect_to school_schoolinformations_path
    else
    end
  end

  def schoolpictures
    @pictures = @school.school_pictures
  end
  def schoolpicture
    if request.get?
      @picture = SchoolPicture.new
    else
      @picture = @school.school_pictures.create(schoolpicture_params)
        if @picture.save
          @school.create_picture(params[:images]) if params[:images]
          redirect_to school_schoolpictures_path
        else 
        end
    end 
  end
  def update_schoolpicture
    if request.get?
      @picture = SchoolPicture.find(params[:school_id])
    else
      @picture = SchoolPicture.find(params[:school_id])
      if @picture.update(schoolpicture_params)
        redirect_to school_schoolpictures_path
      else
      end
    end
  end
  def destroy_schoolpicture
    @picture = SchoolPicture.find(params[:school_id])
    if @picture.destroy
      redirect_to school_schoolpictures_path
    else
    end
  end

  def schoolvideos
    @videos = @school.school_videos
  end
  def schoolvideo
    if request.get?
      @video = SchoolVideo.new
    else
      @video = @school.school_videos.create(schoolvideo_params)
        if @video.save
          redirect_to school_schoolvideos_path
        else 
        end
    end 
  end
  def update_schoolvideo
    if request.get?
      @video = SchoolVideo.find(params[:school_id])
    else
      @video = SchoolVideo.find(params[:school_id])
      if @video.update(schoolvideo_params)
        redirect_to school_schoolvideos_path
      else
      end
    end
  end
  def destroy_schoolvideo
    @video = SchoolVideo.find(params[:school_id])
    if @video.destroy
      redirect_to school_schoolvideos_path
    else
    end
  end

  def requirements
  end
  def post_requirements
    @teacher_post = TeacherRequire.new
    @vendor_post = VendorRequire.new
  end
  def teacher_requirement
    @post = @school.teacher_requires.create(teacher_require_params)
    if @post.save
      redirect_to schools_path
    else 
    end
  end
  def vendor_requirement
    @post = @school.vendor_requires.create(vendor_require_params)
    if @post.save
      redirect_to schools_path
    else 
    end
  end

  private

  def set_school
      @school = User.find_by_id(current_user)
  end

  def overview_params
    params.require(:overview).permit(:title, :description, :user_id, :user_type)
  end

  def course_params
    params.require(:course).permit(:course_name,:degree_name,:course_duration,:course_type,
     :course_fee,:course_affliation,:course_description,:user_id,:new_course_name,:new_degree_name)
  end

  def scholar_params
    params.require(:scholarship).permit(:title, :description, :user_id)
  end

  def placement_params
    params.require(:placement).permit(:title, :description, :companies_visited,
      :students_placed, :total_students, :year, :user_id)
  end

  def cutoff_params
    params.require(:cutoff).permit(:name, :category,:rank, :examination, :percentage,
     :user_id)
  end

  def campu_params
    params.require(:campu).permit(:title, :description, :user_id)
  end

  def news_params

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_left.html.erb
<div id="left">
  <div class="media user-media bg-dark dker">
    <div class="user-media-toggleHover">
      <span class="fa fa-user"></span>
    </div>
    <div class="user-wrapper bg-dark">
      <a class="user-link" href="">
        <%if current_user.profile_image.present? %>
          <%= image_tag current_user.profile_image.url,class: "media-object img-thumbnail user-img",:size => "80x80" %>
        <%else%>
          <%= image_tag('user.gif',class: "media-object img-thumbnail user-img")%>
        <%end%>
        <span class="label label-danger user-label"><%= current_user.sign_in_count%></span>
      </a>
      <div class="media-body">
        <h5 class="media-heading"><%= current_user.name%></h5>
        <ul class="list-unstyled user-info">
          <li><%= current_user.role%></li>
          <li>Last Access : <br>
            <small><i class="fa fa-calendar"></i>&nbsp;<%= current_user.last_sign_in_at.strftime("%d %B %t at %I:%M %p")%></small>
            <% if current_user.active? %>
              <%= link_to "(Edit Profile)" ,edit_user_registration_path%>
            <%else%>
              <a href="#applyModal" data-toggle="modal">(Edit Profile)
              </a>
            <%end%>
          </li>
        </ul>
      </div>
    </div>
  </div>
  
  <ul id="menu" class="bg-blue dker">
    <li class="nav-divider"></li>  
    <li <%if active == 'Dashboard'%> class="active" <%end%>>
      <%= link_to schools_path do%>
        <i class="fa fa-dashboard"></i>
        <span class="link-title" >&nbsp;Dashboard</span>
      <%end%>
    </li>
    <li <%if active == 'Layouts'%> class="active"<%end%>>
      <a href="javascript:;">
        <i class="fa fa-building "></i>
        <span class="link-title">Layouts</span>
        <span class="fa arrow"></span>
      </a>
      <ul class="collapse">
        <li>
          <% if current_user.active? %>
            <%if current_user.overviews.present?%>
              <%= link_to  school_update_overview_path(current_user) do %>
                <i class="fa fa-angle-right"></i>&nbsp;Overview
              <%end%>
          <%else%>
            <%= link_to  school_overview_path(current_user) do %>
              <i class="fa fa-angle-right"></i>&nbsp;Overview
            <%end%>
          <%end%>
        <%else%>
            <a href="#applyModal" data-toggle="modal" class="fa fa-angle-right">Overview</a>
        <%end%>
        </li>
        <li>
          <% if current_user.active? %>
            <%= link_to  school_courses_path(current_user) do %>
            <i class="fa fa-angle-right"></i>&nbsp; Courses<%end%>
          <%else%>
            <a href="#applyModal" data-toggle="modal" class="fa fa-angle-right"> Courses</a>
          <%end%>
        </li>
        <li>
          <% if current_user.active? %>
             <%= link_to  school_scholarships_path(current_user) do %>
          <i class="fa fa-angle-right"></i>&nbsp; Scholarship<%end%>
          <%else%>
            <a href="#applyModal" data-toggle="modal" class="fa fa-angle-right">Scholarship</a>
          <%end%>
        </li>
        <li>
          <% if current_user.active? %>
           <%= link_to  school_placements_path(current_user) do %>
          <i class="fa fa-angle-right"></i>&nbsp; Placement<%end%>
          <%else%>
            <a href="#applyModal" data-toggle="modal" class="fa fa-angle-right">Placement</a>
          <%end%>
        </li>
        <li>
          <% if current_user.active? %>
            <%= link_to  school_cutoffs_path(current_user) do %>
          <i class="fa fa-angle-right"></i>&nbsp; Cutoff<%end%>
          <%else%>
            <a href="#applyModal" data-toggle="modal" class="fa fa-angle-right">Cutoff</a>
          <%end%>
        </li>
        <li>
          <% if current_user.active? %>
            <%= link_to  school_campus_path(current_user) do %>
          <i class="fa fa-angle-right"></i>&nbsp; Campus<%end%>
          <%else%>
            <a href="#applyModal" data-toggle="modal" class="fa fa-angle-right">Campus</a>
          <%end%>
        </li>
        <li>
          <% if current_user.active? %>
            <%= link_to  school_schoolinformations_path(current_user) do %>
          <i class="fa fa-angle-right"></i>&nbsp; News<%end%>
          <%else%>
            <a href="#applyModal" data-toggle="modal" class="fa fa-angle-right">News</a>
          <%end%>
        </li>
        <li>
          <% if current_user.active? %>
            <%= link_to  school_schoolpictures_path(current_user) do %>
          <i class="fa fa-angle-right"></i>&nbsp; Pictures<%end%>
          <%else%>
            <a href="#applyModal" data-toggle="modal" class="fa fa-angle-right">Pictures</a>
          <%end%>
        </li>
        <li>
          <% if current_user.active? %>
            <%= link_to  school_schoolvideos_path(current_user) do %>
          <i class="fa fa-angle-right"></i>&nbsp; Videos<%end%>
          <%else%>
            <a href="#applyModal" data-toggle="modal" class="fa fa-angle-right">Videos</a>
          <%end%>
        </li>
      </ul>
    </li>
    <li <%if active == 'Teachers'%> class="active" <%end%> >
      <% if current_user.active? %>
        <%= link_to  school_teachers_path(current_user) do %>
          <i class="fa fa-tasks"></i>
          <span class="link-title">Teachers</span>
        <%end%>
      <%else%>
        <a href="#applyModal" data-toggle="modal" class="fa fa-tasks" class="link-title">Teachers</a>
      <%end%>
    </li>
    <li <%if active == 'Students'%> class="active"<%end%> >
      <% if current_user.active? %>
        <%= link_to  school_students_path(current_user) do %>
          <i class="fa fa-tasks"></i>
          <span class="link-title">Students</span>
        <%end%>
      <%else%>
        <a href="#applyModal" data-toggle="modal" class="fa fa-tasks" class="link-title">Students</a>
      <%end%>
    </li>
    <li <%if active == 'Vendors'%>  class="active"<%end%> >
      <% if current_user.active? %>
        <%= link_to  school_vendors_path(current_user) do %>
          <i class="fa fa-table"></i>
          <span class="link-title">Vendors</span>
        <%end%>
      <%else%>
        <a href="#applyModal" data-toggle="modal" class="fa fa-table" class="link-title">Vendors</a>
      <%end%>
    </li>
    <li <%if active == 'Post'%>  class="active"<%end%> >
      <% if current_user.active? %>
        <%= link_to  school_post_requirements_path(current_user) do %>
          <i class="fa fa-table"></i>
          <span class="link-title">Post Requirements</span>
        <%end%>
      <%else%>
        <a href="#applyModal" data-toggle="modal" class="fa fa-table" class="link-title">Post Requirements</a>
      <%end%>
    </li>
    <li>
      <% if current_user.active? %>
        <a href="">
          <i class="fa fa-font"></i>
          <span class="link-title">Total Earning</span>
        </a>
      <%else%>
        <a href="#applyModal" data-toggle="modal" class="fa fa-font" class="link-title">Total Earning</a>
      <%end%>
    </li>
    <li class="nav-divider"></li>
  </ul>
</div>

app/views/schools/courses.html.erb
<title>Courses</title>
<meta name="viewport" content="width=device-width, initial-scale=1">

<%= render "layouts/stylesheets"%>

<style type="text/css">
     .ADDcorsen.text-right {
  padding: 20px 0;
}
</style> 

<div class="bg-dark dk" id="wrap">
  <%= render "schools/top"%>
  <%= render :partial => "schools/left", :locals => { :active => 'Layouts' }%>
  <div id="content">
    <div class="outer">
      <div class="inner bg-light lter">
        <h4>List of Courses</h4>
        <hr>
        <div class="ADDcorsen text-right">
          <%=link_to "Back",schools_path, class: "btn btn-primary"%>
          <%=link_to "Add Course",school_course_path(current_user), class: "btn btn-primary"%>
        </div> 
        <div class="table-responsive"> 
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Course Name</th>
                <th>Duration</th>
                <th>Fees</th>
                <th>Action</th>
              </tr>
            </thead>
            <% @courses.each do |course|%>
              <tbody>
                <tr>
                  <td><%= course.course_name%></td>
                  <td><%= course.course_duration%></td>
                  <td><%= course.course_fee%></td>
                  <td>
                    <%=link_to "Edit", school_update_course_path(course),class: "btn btn-primary btn-xs"%>
                    <%=link_to "Delete", school_destroy_course_path(course),class: "btn btn-danger btn-xs", :confirm => "Are you sure you want to delete?"%>
                  </td>
                </tr>
              </tbody>
            <%end%>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>

<div id="helpModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                    culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<%= render "layouts/javascripts"%>

app/views/schools/cutoffs.html.erb
<title>Cut off</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= render "layouts/stylesheets"%>

<style type="text/css">
     .ADDcorsen.text-right {
  padding: 20px 0;
}
</style> 

<div class="bg-dark dk" id="wrap">
  <%= render "schools/top"%>
  <%= render :partial => "schools/left", :locals => { :active => 'Layouts' }%>
  <div id="content">
    <div class="outer">
      <div class="inner bg-light lter">
        <h4>Criteria</h4>
        <hr>
        <div class="ADDcorsen text-right">
          <%=link_to "Back",schools_path, class: "btn btn-primary"%>
          <%=link_to "Add Cutoff",school_cutoff_path(current_user), class: "btn btn-primary"%>
        </div> 
        <div class="table-responsive"> 
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Category</th>
                <th>Examination</th>
                <th>Percentage</th>
                <th>Action</th>
              </tr>
            </thead>
            <% @cutoffs.each do |cutoff|%>
              <tbody>
                <tr>
                  <td><%= cutoff.name%></td>
                  <td><%= cutoff.category%></td>
                  <td><%= cutoff.examination%></td>
                  <td><%= cutoff.percentage%></td>
                  <td>
                    <%=link_to "Edit", school_update_cutoff_path(cutoff),class: "btn btn-primary btn-xs"%>
                    <%=link_to "Delete", school_destroy_cutoff_path(cutoff),class: "btn btn-danger btn-xs", data: {confirm: "Are you sure?"}%>
                  </td>
                </tr>
              </tbody>
            <%end%>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>

<div id="helpModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                    culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<%= render "layouts/javascripts"%>

app/views/schools/scholarships.html.erb
<title>Scholarship</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= render "layouts/stylesheets"%>
<style type="text/css">
     .ADDcorsen.text-right {
  padding: 20px 0;
}
</style> 

<div class="bg-dark dk" id="wrap">
  <%= render "schools/top"%>
  <%= render :partial => "schools/left", :locals => { :active => 'Layouts' }%>
  <div id="content">
    <div class="outer">
      <div class="inner bg-light lter">
        <h4>List of Scholarships</h4>
        <div class="ADDcorsen text-right">
          <%=link_to "Back",schools_path, class: "btn btn-primary"%>
          <%=link_to "Add Scholarships",school_scholarship_path(current_user), class: "btn btn-primary"%>
        </div> 
        <div class="table-responsive"> 
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Action</th>
              </tr>
            </thead>
            <% @scholars.each do |schloar|%>
              <tbody>
                <tr>
                  <td><%= schloar.title%></td>
                  <td><%= schloar.description%></td>
                  <td>
                    <%=link_to "Edit", school_update_scholarship_path(schloar),class: "btn btn-primary btn-xs"%>
                    <%=link_to "Delete", school_destroy_scholarship_path(schloar),class: "btn btn-danger btn-xs", data: {confirm: "Are you sure?"}%>
                  </td>
                </tr>
              </tbody>
            <%end%>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<footer class="Footer bg-dark dker">
    <p>2017 &copy; Tabashi Technology Private Limited</p>
</footer>

<div id="helpModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                    culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<%= render "layouts/javascripts"%>